services:

  db:
    image: postgres:15
    container_name: trains_db
    restart: always

    environment:
      POSTGRES_DB: TrainDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    profiles: ["backend"]

    build: .

    container_name: trains_backend

    ports:
      - "8080:8080"

    depends_on:
      - db

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TrainDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    profiles: ["frontend"]

    build:
      context: ./frontend

    container_name: trains_frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data: